services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    environment:
      - SCYLLA_USER=scylla
      - SCYLLA_PASSWORD=scylla
    ports:
      - "9042:9042"  # Cassandra default port for CQL
    volumes:
      - scylla_data:/var/lib/scylla

  telegram-app:
    build: ./telegram_app
    container_name: telegram-app
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      RABBITMQ_HOST: amqp://rabbitmq
      TICKER_REQUEST_QUEUE: ticker_requests
      TICKER_RESPONSE_QUEUE: ticker_responses
      NOTIFICATION_QUEUE: indicator_notifications
    depends_on:
      - rabbitmq
    restart: on-failure
  
  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    environment:
      RABBITMQ_HOST: amqp://rabbitmq
      TICKER_REQUEST_QUEUE: ticker_requests
      TICKER_RESPONSE_QUEUE: ticker_responses
      TASK_QUEUE: indicator_tasks
      RESULTS_QUEUE: indicator_results 
      NOTIFICATION_QUEUE: indicator_notifications
      SCYLLA_HOST: scylla
      SCYLLA_KEYSPACE: production_keyspace
      SCYLLA_DATACENTER: datacenter1
      SCYLLA_USERNAME: scylla
      SCYLLA_PASSWORD: scylla
    depends_on:
      - scylla
      - rabbitmq
    restart: on-failure

  indicator-app:
    build: ./indicator_app
    container_name: indicator-app
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    restart: on-failure
  
volumes:
  scylla_data: