FROM python:3.12 AS builder

ENV POSTGRES_HOST=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postgres

RUN pip install poetry==1.8.3

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /app

COPY ta-lib-0.4.0-src.tar.gz ./

RUN tar -xzf ta-lib-0.4.0-src.tar.gz

WORKDIR /app/ta-lib

RUN ./configure --prefix=/usr && \
    make && \
    make install

WORKDIR /app/tradingcore

COPY pyproject.toml poetry.lock ./
RUN poetry lock
RUN poetry install

RUN touch README.md

COPY tradingcore ./tradingcore

RUN poetry build
